# Tip:
# If one wants to override the default names of schema.sql and data.sql-old, Spring Boot
# provides us with the configuration properties, which we can use to control
# spring.datasource.schema and spring.datasource.data.

# After Spring Boot 1.3.0.M1, the following property doesn't work:
# spring.data.rest.base-uri=repositories/
# You have to use the following property:
#spring.data.rest.base-path=/repositories

spring:
  profiles:
    active: h2
---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:~/alarmservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverclassName: org.mariadb.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /repositories
  jackson:
    serialization:
      indent_output: true
h2:
 tcp:
  enabled: true
---
spring:
  profiles: mysql
  datasource:
      url: jdbc:mariadb://localhost:3306/alarmservice
      username: root
      password: root
---
spring:
  profiles: mariadb-docker
  datasource:
      url: jdbc:mariadb://localhost:3301/alarmservice
      username: admin
      password: admin

